
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Copy profiles.yml
        env:
          config: ${{ secrets.DBT_PROFILES }}          
        run: |
          mkdir -p $HOME/.dbt
          echo -e "$config" > $HOME/.dbt/profiles.yml      

      - name: Installs dbt
        run: pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery

      - name: Install lightdash CLI
        run: npm install -g @lightdash/cli

      - name: Create config file 
        env: 
          config: ${{ secrets.CLI_CONFIG }}          
        run:  |
          mkdir -p $HOME/.config/lightdash
          echo -e "$config" > $HOME/.config/lightdash/config.yaml

      - name: cli deploy 
        env:
          LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}          
          LIGHTDASH_PROJECT: ${{ secrets.LIGHTDASH_PROJECT }}          
          LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}          

        run: lightdash deploy --project-dir .
