version: 2

models:
  - name: actor
    description: Actor table

    columns:
      - name: actor_id
        description: actor_id
        tests:
          - unique
          - not_null
        meta:
          metrics:
            unique_actor_count:
              type: count_distinct

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: last_update
        description: Timestamp (UTC) when customer was updated
        meta:
          metrics:
            date_of_first_created_customer:
              type: min
            date_of_most_recent_created_customer:
              type: max
